language: erlang

script:
    - make deps
    - make check

otp_release:
    - R15B
    - R15B01
    - R15B02
    - R15B03
    - R16B
    - R16B01
    - R16B02
    - R16B03
    - 17.0
    - 17.1
    - 18.0
    - 18.1
    - 18.2
    - 18.3
    - 19.0
    - 19.1
